### ISSUE TITLE
ImportError: cannot import name 'OffloadedCache' from 'transformers.cache_utils' 

### ISSUE THREAD

**Issue by xueqing0622** [AIFSH/OmniGen-ComfyUI#18]
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\OmniGen-ComfyUI\__init__.py", line 17, in <module>
    from OmniGen import OmniGenPipeline
  File "F:\ComfyUI\ComfyUI\custom_nodes\OmniGen-ComfyUI\OmniGen\__init__.py", line 3, in <module>
    from .scheduler import OmniGenScheduler
  File "F:\ComfyUI\ComfyUI\custom_nodes\OmniGen-ComfyUI\OmniGen\scheduler.py", line 6, in <module>
    from transformers.cache_utils import Cache, DynamicCache, OffloadedCache
ImportError: cannot import name 'OffloadedCache' from 'transformers.cache_utils' (F:\ComfyUI\python_embeded\Lib\site-packages\transformers\cache_utils.py)

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\OmniGen-ComfyUI module for custom nodes: cannot import name 'OffloadedCache' from 'transformers.cache_utils' (F:\ComfyUI\python_embeded\Lib\site-packages\transformers\cache_utils.py)

**Comment by Dan0627** [comment]
一样的问题，这个要怎么解决呀

**Comment by TheLocalLab** [comment]
Upgrade your comfyui transformers library to the latest version. Run `.\python_embeded\python.exe -m pip install --upgrade transformers`  in the directory containing the python_embeded folder if your running the portable version or just `pip install --upgrade transformers` if you installed comfy with your own python package.
