### ISSUE TITLE
NameError: name 'gc' is not defined

### ISSUE THREAD

**Issue by jasoncow007** [AIFSH/OmniGen-ComfyUI#25]
Generating with prompt: the girl in <|image_1|> is dancing on the top of moutain
Before inference: VRAM: Total 16.00GB | Reserved 9.22GB | Allocated 9.15GB | Free -2.37GB
After inference: VRAM: Total 16.00GB | Reserved 10.25GB | Allocated 9.15GB | Free -3.40GB
Cleaning up pipeline
!!! Exception during processing !!! name 'gc' is not defined
Traceback (most recent call last):
File "D:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "D:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "D:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
process_inputs(input_dict, i)
File "D:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "D:\ComfyUI-aki-v1.2\custom_nodes\OmniGen-ComfyUI\nodes.py", line 115, in gen
gc.collect()
NameError: name 'gc' is not defined

**Comment by lbwnb666-ai** [comment]
打开\ComfyUI_windows_portable\ComfyUI\custom_nodes\OmniGen-ComfyUI\nodes.py文件，在代码顶部添加  import gc
作者居然把这个库忘记导入了

**Comment by jasoncow007** [comment]
> 打开\ComfyUI_windows_portable\ComfyUI\custom_nodes\OmniGen-ComfyUI\nodes.py文件，在代码顶部添加 import gc 作者居然把这个库忘记导入了

还有就是这个模型的生成效率太低了，一张图好久，有没有办法在latent上做文章使其能batch生成，反正都是等

**Comment by lbwnb666-ai** [comment]
他的结构注定了效率不会太高，因为他使用的是Transformers架构，而不是UNet架构，与latent没有关系

**Comment by jasoncow007** [comment]
> 他的结构注定了效率不会太高，因为他使用的是Transformers架构，而不是UNet架构，与latent没有关系

感谢答疑，transformer架构的模型没有前空间的概念，能有其他方法实现类似帧绘图的功能么，按照提示词序列批量生成图片

**Comment by lbwnb666-ai** [comment]
为什么不试试AnimateDiff呢，他或许可以完成你的需求（帧绘图）。或者使用提示词批次节点，按照提示词批量绘图。

**Comment by jasoncow007** [comment]
> 为什么不试试AnimateDiff呢，他或许可以完成你的需求（帧绘图）。或者使用提示词批次节点，按照提示词批量绘图。

我也不是需要变化小的连续帧，考虑到ominigen的一致性有所改善，想通过它来看看能否实现角色多大幅度动作的一致性

**Comment by jasoncow007** [comment]
> 为什么不试试AnimateDiff呢，他或许可以完成你的需求（帧绘图）。或者使用提示词批次节点，按照提示词批量绘图。

角色一致性至今没有很好的解决方案，lora的训练成本太高了，换衣服就需要重新训练，transformer架构的视觉特性，提供了一个思路
