### ISSUE TITLE
Workflow never finishes - log errors loading files

### ISSUE THREAD

**Issue by adamreading** [AIFSH/OmniGen-ComfyUI#3]
Hi - when I try and run this I get the same errors each time…
Is there some way of loading the files manually - if so where should they sit?

Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]
Fetching 10 files:  10%|█         | 1/10 [00:00<00:05,  1.58it/s]
Fetching 10 files:  30%|███       | 3/10 [00:00<00:01,  4.53it/s]Error handling request
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/data/app/server.py", line 63, in cache_control
    response: web.Response = await handler(request)
  File "/data/app/server.py", line 141, in origin_only_middleware
    response = await handler(request)
  File "/data/app/server.py", line 75, in cors_middleware
    response = await handler(request)
  File "/data/app/custom_nodes/ComfyUI-Custom-Scripts/py/workflows.py", line 56, in save_workflow
    with open(file, "w") as f:
OSError: [Errno 5] Input/output error
Error handling request
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(requ

**Comment by adamreading** [comment]
If it helps anyone else - it was just the model.safetensor that wouldnt load whilst running - so I manually added it into the structure from the Hugginface repository. it goes in  /models/AIFSH/Shitao/OmniGen-v1/

**Comment by mixoadrian** [comment]
![image](https://github.com/user-attachments/assets/c3842d93-a037-41a2-9dbb-e3a8d73e7013)
I might have a similar issue, files keep loading but stuck there.
mine however didnt show error and not knowing what file is missing.
@adamreading which file you end up missing and did you solve it?

**Comment by adamreading** [comment]
> ![image](https://private-user-images.githubusercontent.com/187217549/382605474-c3842d93-a037-41a2-9dbb-e3a8d73e7013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Njk5NTcsIm5iZiI6MTczMDY2OTY1NywicGF0aCI6Ii8xODcyMTc1NDkvMzgyNjA1NDc0LWMzODQyZDkzLWEwMzctNDFhMi05ZGJiLWUzYThkNzNlNzAxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMTM0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzRmYWUyZWFmNWMxMjZlN2FlNjkwZThmNmNiYmFhNTI5Yzc3NWE3YTk4ZjVjMGU3NzMyNzNmODkxMjk4MGFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NwqqEwm0fktqx9anQSlyqvVFC5jXBJ0_vW62xHhnxb8) I might have a similar issue, files keep loading but stuck there. mine however didnt show error and not knowing what file is missing. @adamreading which file you end up missing and did you solve it?

Just exactly what I mentioned above, for me it was the model.tensor 15gb main file from https://huggingface.co/Shitao/OmniGen-v1/tree/main
